name: ci-nullplatform
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  packages: read
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Start Nullplatform CI
        id: setup-ci
        uses: nullplatform/github-action-setup-ci@v1
        with:
          api-key: ${{ secrets.NULLPLATFORM_API_KEY }}
    outputs:
      application-id: ${{ steps.setup-ci.outputs.application-id }}
      application-name: ${{ steps.setup-ci.outputs.application-name }}
      build-id: ${{ steps.setup-ci.outputs.build-id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        asset: [lambda, docker-image]
    steps:
      - name: Get build parameters
        id: get-build-parameters
        uses: nullplatform/github-action-secrets-and-variables@v1
        with:
          api-key: ${{ secrets.NULLPLATFORM_API_KEY }}
          application-id: ${{ needs.prepare.outputs.application-id }}
      - name: Build asset for ${{ needs.prepare.outputs.application-name }} and asset type {{ matrix.asset }}
        id: build-asset
        uses: nullplatform/github-action-asset-build@v1
        with:
          name: ${{ matrix.asset }}-asset
          type: ${{ matrix.asset }}
          arguments: build-${{ matrix.asset }}
      - name: Push asset for ${{ needs.prepare.outputs.application-name }} and asset type {{ matrix.asset }}
        id: push-asset
        uses: nullplatform/github-action-asset-push@v1
        with:
          name: ${{ matrix.asset }}-asset
          build-id: ${{ needs.prepare.outputs.build-id }}
          type: ${{ matrix.asset }}
    outputs:
      build-id: ${{ needs.prepare.outputs.build-id }}
      status: ${{ contains(fromJSON('["failure", "cancelled"]'), job.status) && 'failed' || 'successful' }}
  finalize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: End Nullplatform CI
        if: ${{ always() }}
        id: end-setup-ci
        uses: nullplatform/github-action-setup-ci@v1
        with:
          api-key: ${{ secrets.NULLPLATFORM_API_KEY }}
          build-id: ${{ needs.build.outputs.build-id }}
          status: ${{ needs.build.outputs.status }}
